language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-renderer-jade hexo-renderer-stylus


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "dantefung"
  - git config user.email "476400902@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${hexoBlog}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-src
env:
 global:
   - GH_REF: github.com/dantefung/dantefung.github.io.git