name: Gitee repos mirror periodic job
on:
  push:
    branches:
      - blog-src
# 如果需要PR触发把push前的#去掉
#on:
  #schedule:
    # 每天北京时间9点跑
    #- cron:  '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Hub Mirror Action.
      uses: Yikun/hub-mirror-action@v0.08
      with:
        src: github/dantefung.github.io
        dst: gitee/dantefung.github.io
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: user
